### PR TITLE
svc/windows: support closing via context.Done()

### LINKED ISSUE #14: Add Context.Done() handling for Windows Service
See #13  /cc @jehiah

### PR DESCRIPTION
**Pull request by jehiah**
This provides support for closing a windows service, and a program running on windows via context.Done() matching non-windows functionality from #13

Closes #14

### CODE REVIEW

**Comment by jehiah** [comment]
@judwhite oops oversight on my part for not including this in the first round - I don't have an environment to test this from so flying a little blind here, but from a read of the code i think this will work for running on windows (easy case) and running as a service (a few more moving parts).

**Comment by jehiah** [comment]
@judwhite let me know if you have any feedback on this - or if you notice anything i need to adjust.

**Comment by judwhite** [comment]
@jehiah I think it looks good. I'm going to do some testing and hopefully get it merged/tagged in the next couple days. Thanks for the ping.

**Comment by jehiah** [comment]
Hey @judwhite i want to follow up on this thread - Is there any additional work i can do here to help?

**Comment by judwhite** [comment]
@jehiah I'm going to add some tests before tagging this. Thanks for the change, I apologize for the delay

**Pull request merged**
